
INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('SCALNT00','BS_SearchCustomerAccountLastNTransactions' ,'BS.SEARCH.CUST.ACCT.LASTN.TRAN.RQ' ,'BS.SEARCH.CUST.ACCT.LASTN.TRAN.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','SCALNT00');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','SCALNT00');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('SCAA010','BS_SearchCustomerAllAccountsService' ,'BS.SEARCH.CUSTOMER.ALL.ACCOUNTS.RQ' ,'BS.SEARCH.CUSTOMER.ALL.ACCOUNTS.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','SCAA010');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','SCAA010');



INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('UCAN07','UpdateCustomerAccountNickname' ,'ESB.COMMON.UPDATE.CUSTOMER.ACCOUNT.NICKNAME.RQ' ,'ESB.COMMON.UPDATE.CUSTOMER.ACCOUNT.NICKNAME.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','UCAN07');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','UCAN07');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('SCALNC01','T24_SearchCustomerAccountLastNTransCount' ,'ESB.T24.SEARCH.CUST.ACCT.LASTN.COUNT.RQ' ,'ESB.T24.SEARCH.CUST.ACCT.LASTN.COUNT.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','SCALNC01');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','SCALNC01');

INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('GCADT01','GetCustomerAccountDetailsService' ,'ESB.GET.CUSTOMER.ACCOUNT.DETAILS.RQ' ,'ESB.GET.CUSTOMER.ACCOUNT.DETAILS.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','GCADT01');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','GCADT01');
           
 
INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('SCAA011','T24_SearchCustomerAllAccountsService' ,'ESB.T24.SEARCH.CUSTOMER.ALL.ACCOUNTS.RQ' ,'ESB.T24.SEARCH.CUSTOMER.ALL.ACCOUNTS.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','SCAA011');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','SCAA011');

INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('GODD001','GetCustomerAccountOverDraftDetailsService' ,'ESB.GET.CUSTOMER.ACCOUNT.OVER.DRAFT.DETAILS.RQ' ,'ESB.GET.CUSTOMER.ACCOUNT.OVER.DRAFT.DETAILS.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','GODD001');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','GODD001');

INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('UCAN08','T24_UpdateCustomerAccountNickname' ,'T24.UPDATE.CUSTOMER.ACCOUNT.NICKNAME.RQ' ,'T24.UPDATE.CUSTOMER.ACCOUNT.NICKNAME.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','UCAN08');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','UCAN08');

INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('SCALNT01','T24_SearchCustomerAccountLastNTransactions' ,'ESB.T24.SEARCH.CUST.ACCT.LASTN.TRAN.RQ' ,'ESB.T24.SEARCH.CUST.ACCT.LASTN.TRAN.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','SCALNT01');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','SCALNT01');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('GCADT03','ICBS_GetCustomerAccountDetailsService' ,'ESB.ICBS.GET.CUSTOMER.ACCOUNT.DETAILS.RQ' ,'ESB.ICBS.GET.CUSTOMER.ACCOUNT.DETAILS.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','GCADT03');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','GCADT03');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('GODD003','ICBS_GetOverDraftDetailsService' ,'ESB.ICBS.GET.OVER.DRAFT.DETAILS.RQ' ,'ESB.ICBS.GET.OVER.DRAFT.DETAILS.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','GODD003');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','GODD003');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('SCALNT02','ICBS_SearchCustomerAccountLastNTransactions' ,'ESB.ICBS.SEARCH.CUST.ACCT.LASTN.TRAN.RQ' ,'ESB.ICBS.SEARCH.CUST.ACCT.LASTN.TRAN.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','SCALNT02');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','SCALNT02');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('SCAA012','ICBS_SearchCustomerAllAccounts' ,'ESB.ICBS.SEARCH.CUSTOMER.ALL.ACCOUNTS.RQ' ,'ESB.ICBS.SEARCH.CUSTOMER.ALL.ACCOUNTS.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','SCAA012');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','SCAA012');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('UCAN09','ICBS_UpdateCustomerAccountNickname' ,'ICBS.UPDATE.CUSTOMER.ACCOUNT.NICKNAME.RQ' ,'ICBS.UPDATE.CUSTOMER.ACCOUNT.NICKNAME.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','UCAN09');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','UCAN09');

INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('GODD002','T24_GetOverDraftDetailsService' ,'ESB.T24.GET.OVER.DRAFT.DETAILS.RQ' ,'ESB.T24.GET.OVER.DRAFT.DETAILS.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','GODD002');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','GODD002');



INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('GCADT02','T24_GetCustomerAccountDetailsService' ,'ESB.T24.GET.CUSTOMER.ACCOUNT.DETAILS.RQ' ,'ESB.T24.GET.CUSTOMER.ACCOUNT.DETAILS.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','GCADT02');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','GCADT02');

 