INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('GCCP000','BS_GetCorporateCustomerProfileService' ,'BS.GET.CORP.CUST.PROFILE.SERVICE.RQ' ,'BS.GET.CORP.CUST.PROFILE.SERVICE.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','GCCP000');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','GCCP000');
 
 INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('GCRP000','BS_GetRetailCustomerProfileService' ,'BS.GET.RETAIL.CUSTOMER.PROFILE.SERVICE.RQ' ,'BS.GET.RETAIL.CUSTOMER.PROFILE.SERVICE.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','GCRP000');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','GCRP000');
 

INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('GCCP004','ICBS_GetCorporateCustomerProfile' ,'ESB.ICBS.GET.CORP.CUST.PROFILE.SERVICE.RQ' ,'ESB.ICBS.GET.CORP.CUST.PROFILE.SERVICE.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','GCCP004');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','GCCP004');

INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('GCCP002','T24_GetCorporateCustomerProfile' ,'ESB.T24.GET.CORP.CUST.PROFILE.SERVICE.RQ' ,'ESB.T24.GET.CORP.CUST.PROFILE.SERVICE.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','GCCP002');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','GCCP002');

INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('GCRP001','T24_GetRetailCustomerProfile' ,'ESB.T24.GET.RETAIL.CUSTOMER.PROFILE.RQ' ,'ESB.T24.GET.RETAIL.CUSTOMER.PROFILE.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','GCRP001');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','GCRP001');
