DEFINE QLOCAL ('T24.OFS.TRX.ADAPTER.RQ.BACKOUT') DEFPSIST(YES) MAXDEPTH(640000) REPLACE;
DEFINE QLOCAL ('T24.OFS.TRX.ADAPTER.RQ') DEFPSIST(YES) MAXDEPTH(640000) BOQNAME('T24.OFS.TRX.ADAPTER.RQ.BACKOUT') REPLACE;
DEFINE QLOCAL ('T24.OFS.ENQ.ADAPTER.RQ.BACKOUT') DEFPSIST(YES) MAXDEPTH(640000) REPLACE;
DEFINE QLOCAL ('T24.OFS.ENQ.ADAPTER.RQ') DEFPSIST(YES) MAXDEPTH(640000) BOQNAME('T24.OFS.ENQ.ADAPTER.RQ.BACKOUT') REPLACE;
DEFINE QLOCAL ('ESB.IN.AUDIT.T24ADAPTER.BACKOUT') DEFPSIST(YES) MAXDEPTH(640000) REPLACE;
DEFINE QLOCAL ('ESB.IN.AUDIT.T24ADAPTER') DEFPSIST(YES) MAXDEPTH(640000) BOQNAME('ESB.IN.AUDIT.T24ADAPTER.BACKOUT') REPLACE;
DEFINE QLOCAL ('ESB.IN.ERROR.T24ADAPTER.BACKOUT') DEFPSIST(YES) MAXDEPTH(640000) REPLACE;
DEFINE QLOCAL ('ESB.IN.ERROR.T24ADAPTER') DEFPSIST(YES) MAXDEPTH(640000) BOQNAME('ESB.IN.ERROR.T24ADAPTER.BACKOUT') REPLACE;



DEFINE QLOCAL ('TAFJ.T24.OFS.TRX.ADAPTER.RQ.BACKOUT') DEFPSIST(YES) MAXDEPTH(640000) REPLACE;
DEFINE QLOCAL ('TAFJ.T24.OFS.TRX.ADAPTER.RQ') DEFPSIST(YES) MAXDEPTH(640000) BOQNAME('TAFJ.T24.OFS.TRX.ADAPTER.RQ.BACKOUT') REPLACE;