
INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('STDI001','T24_SearchTransferDuplicationInternalService' ,'ESB.T24.SEARCH.DUPLICATION.INTERNAL.RQ' ,'ESB.T24.SEARCH.DUPLICATION.INTERNAL.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','STDI001');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','STDI001');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('STDI000','BS_SearchTransferDuplicationInternal' ,'BS.SEARCH.DUPLICATION.INTERNAL.RQ' ,'BS.SEARCH.DUPLICATION.INTERNAL.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','STDI000');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','STDI000');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('STDI002','ICBS_SearchTransferDuplicationInternal' ,'ESB.ICBS.SEARCH.DUPLICATION.INTERNAL.RQ' ,'ESB.ICBS.SEARCH.DUPLICATION.INTERNAL.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','STDI002');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','STDI002');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('STBC001','SearchTransferBankCode' ,'BS.SEARCH.TRANSFER.BANK.CODE.RQ' ,'BS.SEARCH.TRANSFER.BANK.CODE.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','STBC001');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','STBC001');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('STBC002','T24_SearchTransferBankCode' ,'T24.TRANSFER.SEARCH.TRANSFER.BNK.CODE.RQ' ,'T24.TRANSFER.SEARCH.TRANSFER.BNK.CODE.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','STBC002');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','STBC002');



INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('CIT0001','CreateInternationalTransferService' ,'ESB.CREATE.INTERNATIONAL.TRANSFER.RQ' ,'ESB.CREATE.INTERNATIONAL.TRANSFER.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','CIT0001');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','CIT0001');

INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('CDT0001','CreateDomesticTransferService' ,'ESB.CREATE.DOMESTIC.TRANSFER.RQ' ,'ESB.CREATE.DOMESTIC.TRANSFER.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','CDT0001');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','CDT0001');

INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('CDT0003','ICBS_CreateDomesticTransferService' ,'ESB.ICBS.CREATEDEMOSTICTRANSFER.RQ' ,'ESB.ICBS.CREATEDEMOSTICTRANSFER.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','CDT0003');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','CDT0003');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('CIT0003','ICBS_CreateInternationalTransferService' ,'ESB.ICBS.CREATE.INTERN.TRANS.RQ' ,'ESB.ICBS.CREATE.INTERN.TRANS.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','CIT0003');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','CIT0003');

INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('CDT0002','T24_CreateDomesticTransferService' ,'ESB.T24.CREATE.DOMESTIC.TRANSFER.RQ' ,'ESB.T24.CREATE.DOMESTIC.TRANSFER.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','CDT0002');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','CDT0002');


INSERT INTO MCR_CHANNESBFUNC_TBL  (ESBFUNCID,ESBFUNCNAME,REQUEST_QUEUE_NAME,RESPONSE_QUEUE_NAME)
VALUES ('CIT0002','T24_CreateInternationalTransferService' ,'ESB.T24.CREATE.INTERNATIONAL.TRANSFER.RQ' ,'ESB.T24.CREATE.INTERNATIONAL.TRANSFER.RS');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('22','CIT0002');

INSERT INTO MCR_CHANNAUTH_TBL (CHANNID ,ESBFUNCID) 
VALUES ('11','CIT0002');

